scheduleApp/EduScheduleSite/urls.py
from django.urls import path

from . import views

app_name = 'eduschedulesite'
urlpatterns = [
    path('', views.HomePage, name = 'home'),
    path('about/', views.AboutPage, name = 'about'),
    path('contact/', views.ContactPage, name = 'contact'),
    path('terms/', views.TermsPage, name = 'terms'),
    ]

scheduleApp/scheduleApp/urls.py
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.urls import reverse

from website.admin import custom_admin_site


class EduScheduleSitemap(sitemaps.Sitemap):

    def items(self):
        return ['eduschedulesite:home', 'eduschedulesite:about', 'eduschedulesite:contact', 'eduschedulesite:terms']

    def location(self, item):
        return reverse(item)


sitemaps = {
    'static': EduScheduleSitemap,
}

urlpatterns = [
    path('web/', include('website.urls', namespace = 'website')),
    path('admin/', custom_admin_site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('EduScheduleSite.urls', namespace = 'EduScheduleSite')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name = 'django.contrib.sitemaps.views.sitemap')
]

scheduleApp/website/urls.py
from django.urls import path
from . import views

app_name = 'website'
urlpatterns = [
    path('', views.HomePage, name = 'homepage'),
    path('appointments/', views.MyAppointmentsView, name = 'myappointments'),
    path('appointments/approve/<int:pk>/', views.AppointmentApproveView, name = 'appointmentapprove'),
    path('appointments/edit/<int:pk>/', views.AppointmentEditView, name = 'appointmentedit'),
    path('appointments/comment/<int:pk>/', views.AppointmentCommentView, name = 'appointmentcomment'),
    path('appointments/cancel/<int:pk>/', views.AppointmentCancelView, name = 'appointmentcancel'),

    path('new_appointment/teacher/', views.NewAppointmentFindTeacherView, name = 'newappointmentteacher'),
    path('new_appointment/<int:pk>/', views.NewAppointmentView, name = 'newappointment'),
    path('new_appointment/', views.NewAppointmentRedirectView, name = 'newappointmentredirect'),

    path('my_institution/', views.MyInstitutionView, name = 'myinstitution'),
    path('my_institution/students/', views.MyInstitutionStudentsView, name = 'myinstitutionstudents'),
    path('my_institution/teachers/', views.MyInstitutionTeachersView, name = 'myinstitutionteachers'),
    path('my_institution/unapproved_teachers/', views.MyInstitutionUnapprovedView, name = 'myinstitutionunapproved'),
    path('my_institution/approve/<int:pk>/', views.MyInstitutionUserApproveView, name = 'myinstitutionapprove'),
    path('my_institution/edit/<int:pk>/', views.MyInstitutionUserEditView, name = 'myinstitutionedit'),
    path('my_institution/delete/<int:pk>/', views.MyInstitutionUserDeleteView, name = 'myinstitutiondelete'),

    path('notifications/', views.NotificationsView, name = 'notifications'),
    path('notifications/delete/<int:pk>/', views.NotificationDeleteView, name = 'deletenotification'),

    path('settings/', views.SettingsView, name = 'settings'),
    path('institution_settings/', views.InstitutionSettingsView, name = 'institutionsettings'),

    path('my_account/', views.MyAccountView, name = 'myaccount'),
    path('my_account/delete/', views.DeleteAccountView, name = 'deleteaccount'),

    path('usertype/', views.UserTypeView, name = 'usertype'),
    path('find_institution/usertype/<int:usertype>/', views.FindInstitutionView, name = 'findinstitution'),
    path('register/', views.RegisterRedirectView, name = 'registerredirect'),
    path('register/usertype/0/', views.RegisterView, name = 'registeradmin'),
    path('register/usertype/<int:usertype>/institution/<int:institution_id>/', views.RegisterView, name = 'register'),
    path('register_verify/<uidb64>/<token>/', views.ActivateView, name = 'activate'),
]

scheduleApp/EduScheduleSite/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render


def HomePage(request):
    domain = get_current_site(request).domain
    return render(request, 'EduScheduleSite/index.html', {'domain':domain})


def AboutPage(request):
    return render(request, 'EduScheduleSite/about.html')


def ContactPage(request):
    return render(request, 'EduScheduleSite/contact.html')


def TermsPage(request):
    domain = get_current_site(request).domain
    return render(request, 'EduScheduleSite/terms.html', {'domain':domain})

scheduleApp/EduScheduleSite/templates/EduScheduleSite/about.html
{% extends "EduScheduleSite/base.html" %}
{% load static %}
{% load compress %}
{% block title %}About - EduSchedule{% endblock %}
{% block desc %}EduSchedule was created by three students. Learn more about the project!{% endblock %}
{% block content %}
{% compress css inline %}
<style type="text/css">
#content {
	padding-top:30px;
}
</style>
{% endcompress %}
<div class="container" id="content">
		<h2>About EduSchedule</h2>
		<hr />
		<p>
		The idea for EduSchedule was born when three seniors at Glenbrook South High School - Michael, Thomas, and Daniel - realized the inefficiency involved in scheduling meetings with their teachers.
		They had all experienced the cumbersome process of email exchanges or Google Calendar appointments while trying to coordinate a meeting with a teacher.
		Brainstorming ideas, they also learned that teachers, counselors, and tutors faced the same issues.
		EduSchedule, a simple and modern web app for managing appointments, is the solution they came up with.
		</p>
		<p>
		EduSchedule features a simple sign-up process with an equally simple process for registering an institution.
		The application includes an easy-to-use appointment booking and management interface, providing options to edit and cancel appointments.
		Users receive notifications and can customize them based on their preferences.
		And, for institution administrators, EduSchedule integrates easily with existing technology, requiring only an email address for end-user registration.
		</p>
		<p>
		The software is open source and freely-licensed under the GNU GPLv3. The code is available at <a href="https://github.com/michaelpolinski/EduSchedule">https://github.com/michaelpolinski/EduSchedule</a>.
		</p>
</div>
{% endblock %}

scheduleApp/EduScheduleSite/templates/EduScheduleSite/base.html
{% spaceless %}
<!DOCTYPE html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="index,follow">
<meta name="description" content="{% block desc %}{% endblock %}">
{% load compress %}
{% load static %}
<link rel="stylesheet" href="{% static "website/css/bootstrap.min.css" %}" type="text/css">
{% compress css file %}
<style type="text/css">
.dropdown:hover .dropdown-menu {
    display: block;
}
body {
	padding-top: 56px;
	padding-bottom: 40px;
}
/* show the collapse when navbar toggle is checked */
#navbar-toggle-cbox:checked ~ .collapse {
    display: block;
}
/* the checkbox used only internally; don't display it */
#navbar-toggle-cbox {
  display:none
}
.navbar-toggler {
	margin-bottom: 0px
}
.nav-item > a {
	color:white !important;
	margin-top: 2px;
}
.nav-item:hover > a {
	border-bottom: 4px solid white;
	transition: all 0.2s ease;
}
.nav-item > a {
	border-bottom: 4px solid transparent;
}
.nav-item.active > a {
	border-bottom: 4px solid #007bff;
}
ul.navbar-nav > li.nav-item {
	padding-right: 10px;
	padding-left: 10px;
}
.noise {
	background-image: url("{% static "website/img/noise.png" %}")
}
.navbar-toggler-icon {
	background-image: url("{% static "website/img/menu.svg" %}") !important;
}
@media (min-width: 992px) {
    .col-border:not(:last-child) {
        border-right: 1px solid #d7d7d7;
    }
    .col-border + .col-border {
        border-left: 1px solid #d7d7d7;
        margin-left: -1px;
    }
}
</style>
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }
  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>
{% endcompress %}
<script src="{% static "website/js/jquery.min.js" %}"></script>
<script src="{% static "website/js/popper.min.js" %}"></script>
<script src="{% static "website/js/bootstrap.min.js" %}"></script>
<title>{% block title %}EduSchedule{% endblock %}</title>
</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'EduScheduleSite:home' %}">
  <img src="{% static "website/img/logo.svg" %}" width="30" height="30" class="d-inline-block align-top" alt=""> EduSchedule
  </a>
  <input type="checkbox" id="navbar-toggle-cbox">
  <label for="navbar-toggle-cbox" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </label>
  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto">
    {% url 'EduScheduleSite:home' as home %}
    {% url 'EduScheduleSite:about' as about %}
    {% url 'EduScheduleSite:contact' as contact %}
    {% url 'EduScheduleSite:terms' as terms %}
      <li class="nav-item{% if request.path == home %} active{% endif%}">
        <a class="nav-link" href="{{ home }}">Home</a>
      </li>
      <li class="nav-item{% if about in request.path %} active{% endif%}">
        <a class="nav-link" href="{{ about }}">About</a>
      </li>
      <li class="nav-item{% if contact in request.path %} active{% endif%}">
        <a class="nav-link" href="{{ contact }}">Contact</a>
      </li>
      <li class="nav-item{% if terms in request.path %} active{% endif%}">
        <a class="nav-link" href="{{ terms }}">Terms of service</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
  		<li class="ml-auto">
  			<a href="{% url 'website:homepage' %}" class="btn btn-outline-light">EduSchedule web app</a>
  		</li>
  	</ul>
  </div>
</nav>
<main role="main">
{% block content %}
{% endblock %}
<div class="container">
<hr />
</div>
</main>
<footer class="container">
  <p><img src="{% static "website/img/logo.svg" %}" width="24" height="24" class="d-inline-block align-top" alt=""> EduSchedule &copy; 2018-2019 | <a href="{% url 'EduScheduleSite:terms' %}">Terms of service</a></p>
</footer>
</html>
{% endspaceless %}

scheduleApp/EduScheduleSite/templates/EduScheduleSite/contact.html
{% extends "EduScheduleSite/base.html" %}
{% load static %}
{% load compress %}
{% block title %}Contact - EduSchedule{% endblock %}
{% block desc %}Questions? Get in touch with the developers of EduSchedule.{% endblock %}
{% block content %}
{% compress css inline %}
<style type="text/css">
#content {
	padding-top:30px;
}

.icns a {
	margin: 0 .5em;
}
</style>
{% endcompress %}
<div class="container" id="content">
		<h2>Contact</h2>
		<hr /><br />
		<h3>The EduSchedule developers</h3>
		<br />
		<div class="row">
			<div class="col-md-4">
		        <div class="card shadow-sm">
		        	<div class="card-body">
		        	<h3>Michael Polinski</h3>
		        	<h6>Lead developer</h6>
		        	<hr />
		        	<span class="icns">
			        	<a href="https://michaelpolinski.com/"><img src="{% static "EduScheduleSite/img/web.svg" %}" width="30" height="30" alt="website"></a>
						<a href="https://github.com/michaelpolinski/"><img src="{% static "EduScheduleSite/img/gh.svg" %}" width="30" height="30" alt="GitHub"></a>
			        	<a href="https://www.linkedin.com/in/michaelpolinski/"><img src="{% static "EduScheduleSite/img/li.svg" %}" width="30" height="30" alt="Linked_In"></a>
		        	</span>
		        	</div>
		        </div>
		        <br />
	        </div>
	        <div class="col-md-4">
		        <div class="card shadow-sm">
		        	<div class="card-body">
		        	<h3>Thomas Accardo</h3>
		        	<h6>Front-end developer</h6>
		        	<hr />
		        	<span class="icns">
		        		<a href="https://www.linkedin.com/in/thomas-accardo/"><img src="{% static "EduScheduleSite/img/li.svg" %}" width="30" height="30" alt="Linked_In"></a>
		        	</span>
		        	</div>
		        </div>
		        <br />
	        </div>
	        <div class="col-md-4">
		        <div class="card shadow-sm">
		        	<div class="card-body">
		        	<h3>Daniel Hamill</h3>
		        	<h6>Front-end developer</h6>
		        	<hr />
		        	<span class="icns">
		        	<a href="https://www.linkedin.com/in/daniel-hamill/"><img src="{% static "EduScheduleSite/img/li.svg" %}" width="30" height="30" alt="Linked_In"></a>
		        	</span>
		        	</div>
		        </div>
		        <br />
	        </div>
        </div>
        <br />
        For questions regarding the EduSchedule service or software, please contact Michael by email: <img src="{% static "EduScheduleSite/img/eml.png" %}" height="18">
        <br /><br />
</div>
{% endblock %}

scheduleApp/EduScheduleSite/templates/EduScheduleSite/index.html
{% extends "EduScheduleSite/base.html" %}
{% block title %}EduSchedule - simple, modern appointment management for schools{% endblock %}
{% block desc %}EduSchedule is a simple and modern web app that helps students and teachers manage appointments efficiently. Try EduSchedule at your school today!{% endblock %}
{% block content %}
  <div class="jumbotron noise">
    <div class="container">
      <h1 class="display-4">EduSchedule</h1>
      <h4>a simple and modern web app that helps students and teachers manage appointments efficiently</h4>
      <br />
      <a class="btn btn-primary btn-lg" href="{% url 'website:homepage' %}" role="button">Get started &raquo;</a>
    </div>
  </div>
  <div class="container">
  <h2>Why EduSchedule?</h2>
    <hr /><br />
    <div class="row">
      <div class="col-md-4">
      <div class="card shadow-sm">
      <div class="card-body">
        <h3>
        <svg id="i-lightning" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
    		<path d="M18 13 L26 2 8 13 14 19 6 30 24 19 Z" />
		</svg>
        Simple
        </h3>
        <p>EduSchedule is designed to be simple, modern, and fast without sacrificing usability. Registration requires only an email address.</p>
      </div>
      </div>
      <br />
      </div>
      <div class="col-md-4">
      	<div class="card shadow-sm">
      	<div class="card-body">
        <h3>
        <svg id="i-options" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
    		<path d="M28 6 L4 6 M28 16 L4 16 M28 26 L4 26 M24 3 L24 9 M8 13 L8 19 M20 23 L20 29" />
		</svg>
        Flexible
        </h3>
        <p>Institutions can register for EduSchedule quickly on {{ domain }} or run the software on their servers.</p>
        </div>
        </div>
        <br />
      </div>
      <div class="col-md-4">
      <div class="card shadow-sm">
      <div class="card-body">
        <h3>
        <svg id="i-code" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
    		<path d="M10 9 L3 17 10 25 M22 9 L29 17 22 25 M18 7 L14 27" />
		</svg>
		Open source
		</h3>
        <p>EduSchedule is open-source and freely licensed under the GNU GPL. Check out the code <a href="https://github.com/michaelpolinski/EduSchedule">here</a> - pull requests welcome.</p>
        </div>
        </div>
        <br />
      </div>
    </div>
    <br /><br />
    <a href="{% url 'EduScheduleSite:about' %}" class="btn btn-secondary">Learn more &raquo;</a>&nbsp;
    <a href="{% url 'EduScheduleSite:contact' %}" class="btn btn-secondary">Contact the developers &raquo;</a>
    <br /><br />
  </div>
{% endblock %}

scheduleApp/EduScheduleSite/templates/EduScheduleSite/terms.html
{% extends "EduScheduleSite/base.html" %}
{% load compress %}
{% block title %}Terms of service - EduSchedule{% endblock %}
{% block content %}
{% compress css inline %}
<style type="text/css">
#content {
	padding-top:30px;
}
</style>
{% endcompress %}
<div class="container" id="content">
<h3>Terms of service</h3>
<hr />
<p>Thank you for using EduSchedule!</p>
<p>By using the services provided by EduSchedule on {{ domain }} (the "SERVICE") or by visiting the EduSchedule website at {{ domain }} (the "WEBSITE"), you agree to the following terms.</p>
<br />
<h5>1. Acceptable use</h5>
<p>EduSchedule is provided as a free service. By using the SERVICE or visiting the WEBSITE, you agree that you will not abuse or misuse, by any means, the SERVICE or WEBSITE or any of its users, or use the SERVICE or WEBSITE for any unintended purposes. You agree that service may be refused or suspended at the discretion of the server administrator if this policy is violated.</p>
<br />
<h5>2. Privacy and security</h5>
<p>EduSchedule is committed to protecting your privacy. The information you store through the SERVICE is protected using available technical means and is not shared with other parties. If the privacy of the SERVICE is of concern, you may download the freely-licensed EduSchedule software for use on your own server.
<br />
The developers of EduSchedule take the security of the EduSchedule software seriously. If you believe you have found a security issue, please do not report it publicly; instead, contact the developers directly. Contact information is available <a href="{% url 'EduScheduleSite:contact' %}">here</a>.
</p>
<br />
<h5>3. Disclaimer of warranties</h5>
<p>THE SERVICE AND WEBSITE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF AVAILABILITY OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT SHALL THE PROVIDERS OF THE SERVICE AND THE WEBSITE BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SERVICE OR WEBSITE.</p>
<br />
<h5>4. Changes to the terms</h5>
<p>These terms may be changed at any time without prior notice. If changes are made, they will be found on this page.</p>
<br />
</div>
{% endblock %}