scheduleApp/EduScheduleSite/urls.py
from django.urls import path

from . import views

app_name = 'eduschedulesite'
urlpatterns = [
    path('', views.HomePage, name = 'home'),
    path('about/', views.AboutPage, name = 'about'),
    path('contact/', views.ContactPage, name = 'contact'),
    path('terms/', views.TermsPage, name = 'terms'),
    ]

scheduleApp/scheduleApp/urls.py
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.urls import reverse

from website.admin import custom_admin_site


class EduScheduleSitemap(sitemaps.Sitemap):

    def items(self):
        return ['eduschedulesite:home', 'eduschedulesite:about', 'eduschedulesite:contact', 'eduschedulesite:terms']

    def location(self, item):
        return reverse(item)


sitemaps = {
    'static': EduScheduleSitemap,
}

urlpatterns = [
    path('web/', include('website.urls', namespace = 'website')),
    path('admin/', custom_admin_site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('EduScheduleSite.urls', namespace = 'EduScheduleSite')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name = 'django.contrib.sitemaps.views.sitemap')
]

scheduleApp/website/urls.py
from django.urls import path
from . import views

app_name = 'website'
urlpatterns = [
    path('', views.HomePage, name = 'homepage'),
    path('appointments/', views.MyAppointmentsView, name = 'myappointments'),
    path('appointments/approve/<int:pk>/', views.AppointmentApproveView, name = 'appointmentapprove'),
    path('appointments/edit/<int:pk>/', views.AppointmentEditView, name = 'appointmentedit'),
    path('appointments/comment/<int:pk>/', views.AppointmentCommentView, name = 'appointmentcomment'),
    path('appointments/cancel/<int:pk>/', views.AppointmentCancelView, name = 'appointmentcancel'),

    path('new_appointment/teacher/', views.NewAppointmentFindTeacherView, name = 'newappointmentteacher'),
    path('new_appointment/<int:pk>/', views.NewAppointmentView, name = 'newappointment'),
    path('new_appointment/', views.NewAppointmentRedirectView, name = 'newappointmentredirect'),

    path('my_institution/', views.MyInstitutionView, name = 'myinstitution'),
    path('my_institution/students/', views.MyInstitutionStudentsView, name = 'myinstitutionstudents'),
    path('my_institution/teachers/', views.MyInstitutionTeachersView, name = 'myinstitutionteachers'),
    path('my_institution/unapproved_teachers/', views.MyInstitutionUnapprovedView, name = 'myinstitutionunapproved'),
    path('my_institution/approve/<int:pk>/', views.MyInstitutionUserApproveView, name = 'myinstitutionapprove'),
    path('my_institution/edit/<int:pk>/', views.MyInstitutionUserEditView, name = 'myinstitutionedit'),
    path('my_institution/delete/<int:pk>/', views.MyInstitutionUserDeleteView, name = 'myinstitutiondelete'),

    path('notifications/', views.NotificationsView, name = 'notifications'),
    path('notifications/delete/<int:pk>/', views.NotificationDeleteView, name = 'deletenotification'),

    path('settings/', views.SettingsView, name = 'settings'),
    path('institution_settings/', views.InstitutionSettingsView, name = 'institutionsettings'),

    path('my_account/', views.MyAccountView, name = 'myaccount'),
    path('my_account/delete/', views.DeleteAccountView, name = 'deleteaccount'),

    path('usertype/', views.UserTypeView, name = 'usertype'),
    path('find_institution/usertype/<int:usertype>/', views.FindInstitutionView, name = 'findinstitution'),
    path('register/', views.RegisterRedirectView, name = 'registerredirect'),
    path('register/usertype/0/', views.RegisterView, name = 'registeradmin'),
    path('register/usertype/<int:usertype>/institution/<int:institution_id>/', views.RegisterView, name = 'register'),
    path('register_verify/<uidb64>/<token>/', views.ActivateView, name = 'activate'),
]

scheduleApp/website/views.py
from datetime import datetime, timedelta

from copy import copy
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Q, query
from django.http.response import Http404
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.urls.base import reverse
from django.utils import timezone
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from logging import _startTime
from ratelimit.decorators import ratelimit
from website.forms import DeleteAccountForm, MyInstitutionUserEditForm, \
    MyInstitutionUserDeleteForm, AppointmentCancelForm, AppointmentEditForm, \
    AppointmentCommentForm, FindTeacherForm, NewAppointmentForm
from website.models import Comment

from .forms import FindInstitutionForm, UserTypeForm, RegisterForm, MyAccountForm, StudentSettingsForm, TeacherSettingsForm, AdministratorSettingsForm, InstitutionSettingsForm, NotificationsDeleteForm
from .models import AccountActivationTokenGenerator
from .models import User, Institution, AppointmentNotification, UserNotification, Appointment


def HomePage(request):
    domain = get_current_site(request).domain
    notifications = 0
    institution = None
    if request.user.is_authenticated:
        user = request.user
        institution = user.institution.name
        usertype = user.userType
        tz = user.institution.timezone
        timezone.activate(tz)
        start_time = timezone.now() - timedelta(days = 14)
        end_time = timezone.now()
        if usertype == 0:
            notifications = UserNotification.objects.filter(user = user, datetime__lt = end_time, datetime__gt = start_time).__len__()
        else:
            notifications = AppointmentNotification.objects.filter(user = user, datetime__lt = end_time, datetime__gt = start_time).__len__()
    return render(request, 'website/index.html', {'domain':domain, 'notifications':notifications, 'institution':institution})


@login_required
def MyAppointmentsView(request, time_begin = None, time_end = None):
    user = request.user
    usertype = user.userType
    if time_begin is None or time_end is None or time_begin >= time_end:
            time_begin = timezone.now()
            time_end = timezone.now() + timedelta(days = 30)
    appointments = user.get_appointments(time_begin = time_begin, time_end = time_end)
    overlapping_indices = []
    i = 0
    while i < len(appointments):
        if user.get_overlapping_appointments(appointments[i].startTime, appointments[i].endTime, exclude = appointments[i]) is not None:
            overlapping_indices.append(i)
        i += 1
    try:
        message = request.GET['msg']
    except:
        message = None
    return render(request, 'website/my_appointments.html', {'appointments':appointments, 'usertype':usertype, 'message':message, 'overlapping_indices':overlapping_indices})


@login_required
def AppointmentApproveView(request, pk):
    if not request.method == 'POST':
        return "This endpoint should be accessed via POST request only."
    user = request.user
    usertype = user.userType
    tz = user.institution.timezone
    timezone.activate(tz)
    if usertype == 1:
        appointment = get_object_or_404(Appointment, pk = pk, teacher = user, endTime__gte = timezone.now(), teacherConfirmed = False)
        target_user = appointment.student
        appointment.teacherConfirmed = True
        appointment.previousStartTime = None
        appointment.previousEndTime = None
        # technically not needed, but
        appointment.previousLocation = None
    elif usertype == 2:
        appointment = get_object_or_404(Appointment, pk = pk, student = user, endTime__gte = timezone.now(), studentConfirmed = False)
        target_user = appointment.teacher
        appointment.studentConfirmed = True
        appointment.previousLocation = None
        appointment.previousStartTime = None
        appointment.previousEndTime = None
    else:
        return "This page is intended for teachers and students only."
    appointment.save()
    try:
        notifications_remove = AppointmentNotification.objects.filter(user = user, appointment = appointment).exclude(event = 5)
        notifications_remove.delete()
    finally:
        if target_user.notifyAppointmentApprovedChangedCancelledWeb:
            notification = AppointmentNotification(datetime = timezone.now(), user = target_user, appointment = appointment, event = 0)
            notification.save()
        return redirect(reverse('website:myappointments') + '?msg=approve_success')


@login_required
def AppointmentEditView(request, pk):
    user = request.user
    usertype = user.userType
    tz = user.institution.timezone
    timezone.activate(tz)
    if usertype == 1:
        appointment = get_object_or_404(Appointment, pk = pk, teacher = user, endTime__gte = timezone.now())
        target_user = appointment.student
    elif usertype == 2:
        appointment = get_object_or_404(Appointment, pk = pk, student = user, endTime__gte = timezone.now())
        target_user = appointment.teacher
    else:
        raise Http404()
    commentform = AppointmentCommentForm()
    comments = Comment.objects.filter(appointment = appointment)
    if request.method == 'POST':
        prevStart = copy(appointment.startTime)
        prevEnd = copy(appointment.endTime)
        prevLocation = copy(appointment.location)
        form = AppointmentEditForm(request.POST, instance = appointment, usertype = usertype)
        if form.is_valid():
            updated_appointment = form.save(commit = False)
            change = False
            if not updated_appointment.location == prevLocation:
                updated_appointment.previousLocation = prevLocation
                change = True
            if not (updated_appointment.startTime == prevStart and updated_appointment.endTime == prevEnd):
                updated_appointment.previousStartTime = prevStart
                updated_appointment.previousEndTime = prevEnd
                change = True
            if usertype == 1 and change:
                updated_appointment.studentConfirmed = False
                updated_appointment.teacherConfirmed = True
                notification = AppointmentNotification(datetime = timezone.now(), user = target_user, appointment = updated_appointment, event = 1)
            elif usertype == 2 and change:
                updated_appointment.studentConfirmed = True
                updated_appointment.teacherConfirmed = False
                notification = AppointmentNotification(datetime = timezone.now(), user = target_user, appointment = updated_appointment, event = 1)
            updated_appointment.save()
            try:
                notifications_remove = AppointmentNotification.objects.filter(user = user, appointment = updated_appointment)
                notifications_remove.delete()
            finally:
                if change and target_user.notifyAppointmentApprovedChangedCancelledWeb:
                    notification.save()
                return redirect(reverse('website:myappointments') + '?msg=edit_success')
    else:
        form = AppointmentEditForm(instance = appointment, usertype = usertype)
    return render(request, 'website/appointment_edit.html', {'appointment':appointment, 'form':form, 'commentform':commentform, 'comments':comments, 'usertype':usertype})


@login_required
def AppointmentCommentView(request, pk):
    user = request.user
    usertype = user.userType
    tz = user.institution.timezone
    timezone.activate(tz)
    if usertype == 1:
        appointment = get_object_or_404(Appointment, pk = pk, teacher = user, endTime__gte = timezone.now())
        target_user = appointment.student
    elif usertype == 2:
        appointment = get_object_or_404(Appointment, pk = pk, student = user, endTime__gte = timezone.now())
        target_user = appointment.teacher
    else:
        raise Http404()
    if request.method == 'POST':
        form = AppointmentCommentForm(request.POST)
        if form.is_valid():
            comment = Comment(user = user, appointment = appointment, message = form.cleaned_data['comment'])
            comment.save()
            if target_user.notifyAppointmentCommentWeb:
                notification = AppointmentNotification(datetime = timezone.now(), user = target_user, appointment = appointment, event = 5)
                notification.save()
            return redirect('website:appointmentedit', appointment.pk)
    else:
        return "This endpoint should be accessed via POST request only."


@login_required
def AppointmentCancelView(request, pk):
    user = request.user
    usertype = user.userType
    if usertype == 1:
        appointment = get_object_or_404(Appointment, pk = pk, teacher = user, endTime__gte = timezone.now(), cancelled = False)
        target_user = appointment.student
    elif usertype == 2:
        appointment = get_object_or_404(Appointment, pk = pk, student = user, endTime__gte = timezone.now(), cancelled = False)
        target_user = appointment.teacher
    else:
        raise Http404()
    if request.method == 'POST':
        form = AppointmentCancelForm(request.POST)
        if form.is_valid():
            appointment.cancelled = True
            notification = AppointmentNotification(datetime = timezone.now(), user = target_user, appointment = appointment, event = 2)
            appointment.save()
            try:
                notifications_remove = AppointmentNotification.objects.filter(user = user, appointment = appointment).exclude(event = 5)
                notifications_remove.delete()
            finally:

scheduleApp/website/templates/website/account_activation_email.html
{% autoescape off %}
Thank you for registering on EduSchedule!

Please click on the link below to verify your email address and complete your registration:
{{ protocol }}://{{ domain }}{% url 'website:activate' uidb64=uid token=token %}

If you did not initiate this request to register, simply delete this email.
{% endautoescape %}

scheduleApp/website/templates/website/activation_valid.html
{% extends "website/base.html" %}
{% load compress %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<h3>{% block title %}Registration complete{% endblock %}</h3>
<hr />
<div class="row">
	<div class="col-sm col-border">
				Registration: step 4 of 4
		<div class="progress">
			<div class="progress-bar" role="progressbar" style="width: 100%" aria-valuenow="4" aria-valuemin="0" aria-valuemax="4"></div>
		</div>
		<br />
		<p>Welcome, {{ user.first_name }}! Your registration on EduSchedule is complete and your email address is now confirmed.
		</p>
		{% if is_school_admin %}
		{% if not institution.isVerified %}
		<p>
		Your institution, {{ institution.name }}, is currently pending verification and must be validated by a server administrator, who will check that the institution exists at the specified address. 
		Your identity may also be subject to additional verification. To complete this process, a server administrator will contact you directly.
		</p>
		{% endif %}
		{% endif %}
		<p>You may now configure basic <a href="{% url 'website:settings' %}">settings</a> for your account.</p>
		<p>To change your password and manage your personal information, visit <a href="{% url 'website:myaccount' %}">My Account</a>.</p>
	</div>
</div>

{% endblock %}

scheduleApp/website/templates/website/base.html
{% spaceless %}
<!DOCTYPE html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% load compress %}
{% load static %}
<link rel="stylesheet" href="{% static "website/css/bootstrap.min.css" %}" type="text/css">
{% compress css file %}
<style type="text/css">
.dropdown:hover .dropdown-menu {
    display: block;
}
body {
	padding-top: 80px;
	padding-bottom: 40px;
}
/* show the collapse when navbar toggle is checked */
#navbar-toggle-cbox:checked ~ .collapse {
    display: block;
}
/* the checkbox used only internally; don't display it */
#navbar-toggle-cbox {
  display:none
}
.navbar-toggler {
	margin-bottom: 0px
}
.nav-item > a {
	color:white !important;
	margin-top: 2px;
}
.nav-item:hover > a {
	border-bottom: 4px solid white;
}
.nav-item > a {
	border-bottom: 4px solid transparent;
}
.nav-item.active > a {
	border-bottom: 4px solid #007bff;
}
ul.navbar-nav > li.nav-item {
	padding-right: 10px;
	padding-left: 10px;
}
.asteriskField {
    display: none;
}
.navbar-toggler-icon {
	background-image: url("{% static "website/img/menu.svg" %}") !important;
}
@media (min-width: 992px) {
    .col-border:not(:last-child) {
        border-right: 1px solid #d7d7d7;
    }
    .col-border + .col-border {
        border-left: 1px solid #d7d7d7;
        margin-left: -1px;
    }
}
</style>
{% endcompress %}
<script src="{% static "website/js/jquery.min.js" %}"></script>
<script src="{% static "website/js/popper.min.js" %}"></script>
<script src="{% static "website/js/bootstrap.min.js" %}"></script>
<title>{% block title %}Home{% endblock %} - EduSchedule</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'website:homepage' %}">
  <img src="{% static "website/img/logo.svg" %}" width="30" height="30" class="d-inline-block align-top" alt=""> EduSchedule
  </a>
  <input type="checkbox" id="navbar-toggle-cbox">
  <label for="navbar-toggle-cbox" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </label>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
      {% if user.userType == 2 %}
      {% url 'website:myappointments' as myappts %}
      <li class="nav-item{% if myappts in request.path %} active{% endif%}" >
        <a class="nav-link" href="{{ myappts }}">My Appointments</a>
      </li>
      {% url 'website:newappointmentredirect' as newappt %}
      <li class="nav-item{% if newappt in request.path %} active{% endif%}">
        <a class="nav-link" href="{{ newappt }}">New Appointment</a>
      </li>
      {% endif %}
      
      {% if user.userType == 1 %}
      {% url 'website:myappointments' as myappts %}
      <li class="nav-item{% if myappts in request.path %} active{% endif%}" >
        <a class="nav-link" href="{{ myappts }}">My Appointments</a>
      </li>
      {% endif %}
      
      {% if user.userType == 0 %}
      {% url 'website:myinstitution' as myinst %}
      <li class="nav-item{% if myinst in request.path %} active{% endif%}" >
        <a class="nav-link" href="{{ myinst }}">My Institution</a>
      </li>
      {% url 'website:institutionsettings' as iset %}
      <li class="nav-item{% if iset in request.path %} active{% endif%}">
        <a class="nav-link" href="{{ iset }}">Institution Settings</a>
      </li>
      {% endif %}
      
      {% url 'website:notifications' as notifs %}
      <li class="nav-item{% if notifs in request.path %} active{% endif%}">
        <a class="nav-link" href="{{ notifs }}">Notifications</a>
      </li>
      {% url 'website:settings' as uset %}
      <li class="nav-item{% if uset in request.path %} active{% endif%}">
        <a class="nav-link" href="{{ uset }}">Settings</a>
      </li>
      
      {% endif %}
    </ul>
  <ul class="nav navbar-nav navbar-right">
  {% if user.is_authenticated %}
  	<li class="ml-auto">
  	{% url 'website:myaccount' as myacct %}
  	<a href="{{ myacct }}" class="btn btn-{% if myacct in request.path %}primary{% else %}outline-light{% endif %}">My account</a>&nbsp;
  	<a href="{% url 'logout' %}" class="btn btn-outline-light">Log out</a>
  	</li>
    {% else %}
    <li class="ml-auto">
    <a href="{% url 'login' %}" class="btn btn-outline-light">Sign in</a>&nbsp;
    <a href="{% url 'website:registerredirect' %}" class="btn btn-outline-light">Create account</a>
    </li>
    {% endif %}
  </ul>
</div>
</nav>
<main role="main" class="container">
{% block content %}
{% endblock %}
</main>
</body>
</html>
{% endspaceless %}

scheduleApp/website/templates/website/find_institution.html
{% extends "website/base.html" %}
{% load compress %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<h3>{% block title %}Find your institution{% endblock %}</h3>
<hr />
<div class="row">
	<div class="col-sm col-border">
				Registration: step 2 of 4
		<div class="progress">
			<div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="4"></div>
		</div>
		<br />
		<p>Let's find your institution or school. Search for your school by zip code below.</p>
	<form method="post">
	{% csrf_token %}
	{{ form|crispy }}
	<button type="submit" class="btn btn-primary">Search</button>		
	</form>
	</div>
	<div class="col-sm col-border">
	{% if empty %}
	<h4>Search Results</h4>
	<p>No verified institutions were found registered in EduSchedule's database.</p>
	<p>If your school has not yet joined EduSchedule, ask a school administrator to register the school.</p>
	{% endif %}
	{% if results %}
	<h4>Search Results</h4>
	{% for school in results %}
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">{{school.name}}</h5>
				<h6 class="card-subtitle mb-2 text-muted">{{school.streetAddress}}</h6>
				<h6 class="card-subtitle mb-2 text-muted">{{school.cityState}} {{school.zipcode}}</h6>
				<a href="{% url 'website:register' usertype school.id %}" class="card-link">Continue registration &gt;</a>
  			</div>
		</div>
		<br />
	{% endfor %}
	{% endif %}
	</div>
</div>

{% endblock %}

scheduleApp/website/templates/website/find_teacher.html
{% extends "website/base.html" %}
{% load compress %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<h3>{% block title %}Find a teacher{% endblock %}</h3>
<hr />
<div class="row">
	<div class="col-sm col-border">
	<p>Search for a teacher below by first name, last name, or full name.</p>
	<form method="post">
	{% crispy form %}		
	</form>
	</div>
	<div class="col-sm col-border">
	{% if empty %}
	<h4>Search Results</h4>
	<p>No teachers at your institution matched your search.</p>
	{% endif %}
	{% if results %}
	<h4>Search Results</h4>
	{% for teacher in results %}
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">{{ teacher }}</h5>
				<a href="{% url 'website:newappointment' teacher.pk %}" class="card-link">Continue &gt;</a>
  			</div>
		</div>
		<br />
	{% endfor %}
	{% endif %}
	</div>
</div>

{% endblock %}

scheduleApp/website/templates/website/index.html
{% extends "website/base.html" %}
{% load compress %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<h3>{% block title %}Home{% endblock %}</h3>
<hr />
{% if user.is_authenticated %}
<div class="row">
	<div class="col-sm-8 col-border">
		<p>{{ user.first_name }}, welcome to EduSchedule for {{ institution }} on {{ domain }}.</p>
	</div>
	<div class="col-sm-4 col-border">
		<center>
		<a href="{% url 'website:notifications' %}" class="btn btn-light">
  			Notifications <span class="badge badge-dark">{{ notifications }}</span>
		</a>
		</center>
	</div>
</div>


</p>
{% else %}
<p>Welcome to the EduSchedule web app on {{ domain }}.</p>
<p>Please <a href="{% url 'login' %}">sign in</a> or <a href="{% url 'website:registerredirect' %}">create an account</a> to get started.</p>
<br />
<p>Are you a school administrator? Create an account and register your school for EduSchedule <a href="{% url 'website:registeradmin' %}">here</a>.</p>
<br />
<p><a href={% url 'EduScheduleSite:home' %}>Learn more</a> about EduSchedule and the service we offer.</p>
{% endif %}
<div class="row">
	<div class="col-sm-8 col-border">
	</div>
	<div class="col-sm-4 col-border">
	</div>
</div>

{% endblock %}

scheduleApp/website/templates/website/my_institution_user_delete.html
{% extends "website/base.html" %}
{% load compress %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<h3>{% block title %}Delete user{% endblock %}</h3>
<hr />
<div class="row">
	<div class="col-sm-8">
	<h4>{{ target_user }}</h4>
	<p>{{ target_user.email }} <span class="badge badge-{% if target_user.isEmailConfirmed %}success{% else %}warning{% endif %}">{% if target_user.isEmailConfirmed %}Confirmed{% else %}Unconfirmed{% endif %}</span><br />
	{% if target_user.userType == 1 %}Teacher{% else %}Student{% endif %}<br />
	Last login: {{ target_user.last_login }}</p>
	{% if not target_user.is_active %}<strong> - This user account is disabled -</strong><br />{% endif %}
	<br />
	<div class="alert alert-danger" role="alert">
		<p><strong>Important!</strong> Deleting this user account will delete all associated data, including appointment data and settings. Are you sure you want to proceed?</p>
		<p><i>If this a temporary restriction on the user's account, <a href="{% url 'website:myinstitutionedit' target_user.pk %}">edit the user account instead</a> and set it to <strong>inactive</strong>.</i></p>
	</div>
	<form method="post">
	{% csrf_token %}
	{% crispy form %}
	</form>
	</div>
</div>

{% endblock %}

scheduleApp/website/templates/website/notifications.html
{% extends "website/base.html" %}
{% load compress %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block content %}

{% compress css inline %}
<style type="text/css">
.clear-form {
	margin-bottom: 0px;
}
</style>
{% endcompress %}

<h3>{% block title %}Notifications{% endblock %}</h3>
<hr />
<div class="row">
	<div class="col-sm-8">
	{% if notifications %}
		{% for n in notifications %}
			<div class="card">
				<div class="card-body">
					<div class="row">
						<div class="col-6 col-border">
							<h5><strong>{{ n.notification_title }}</strong></h5>
							{{ n.notification_text }}
						</div>
						<div class="col-6 col-border text-right">
							{% if usertype == 0 %}
								<form action="{% url 'website:myinstitutionapprove' n.target_user.pk %}" method="post">
								{% csrf_token %}
								<div class="btn-group" role="group" aria-label="Action buttons">
									<button type="submit" class="btn btn-{% if n.target_user.isEmailConfirmed %}success{% else %}secondary disabled{% endif %}">Approve</button>
									<a href="{% url 'website:myinstitutionedit' n.target_user.pk %}" class="btn btn-primary">Edit user</a>
			 						<a href="{% url 'website:myinstitutiondelete' n.target_user.pk %}" class="btn btn-danger">Delete user</a>
								</div>
			  					</form>
		  					{% else %}
								<div class="btn-group" role="group" aria-label="Action buttons">
									<a href="{% url 'website:appointmentedit' n.appointment.pk %}" class="btn btn-primary">Details</a>
			 						<a href="{% url 'website:appointmentcancel' n.appointment.pk %}" class="btn btn-danger">Cancel</a>
								</div>
		  					{% endif %}
						</div>
					</div>
				</div>
				<div class="card-footer">
					<div class="row">
					<div class="col-6">
						{{ n.datetime|naturaltime }}
					</div>
					<div class="col-6 text-right">
						<form action="{% url 'website:deletenotification' n.pk %}" method="post" class="clear-form">
							{% csrf_token %}
							<button type="submit" class="btn btn-outline-danger btn-sm">Clear</button>
						</form>
					</div>
					</div>
				</div>
			</div>
			<br />
		{% endfor %}
	{% else %}
	<p>No notifications to display.</p>
	{% endif %}
	</div>
	<div class="col-sm-4">
		{% if not older == 0 %}
			<p>{{ older }} older notification{% if older == 1 %} is{% else %}s are{% endif %} not shown.</p>
		{% endif %}
		{% if success %}
		<div class="alert alert-success" role="alert">
			All notifications have been deleted.
		</div>
		{% endif %}
		<form method="post">
			{% crispy form %}	
		</form>
	</div>
</div>

{% endblock %}